### ISSUE TITLE
cross platform label() API

### ISSUE THREAD

**Issue by kamstrup** [Microsoft/AppCenter-Test-Appium-Java-Extensions#1]
There has been user requests for cross platform APIs for calling label() on a driver.

Maybe we should make the enhanced ios/android drivers implement a LabellingDriver interface and have label(String) be part of that?

Alternatively we could do a full facade that wraps a driver and exposes a label(String) method, dispatching to one of the enhanced drivers by simple instanceof checking.

Neither one is super nice, but we wouldn't want to break API either...

**Comment by krukow** [comment]
Thanks for the suggestion @kamstrup any thoughts @john7doe ?

**Comment by john7doe** [comment]
I like the LabellingDriver route the best and that's certainly something we could do.

**Comment by lughino** [comment]
Hi, any news for this change? Is there an ETA? Appium allow to have cross platform tests.. and it's very useful!

**Comment by OleksiiStr** [comment]
Hello,
@krukow , @john7doe any info about when LabellingDriver could be done?

**Comment by john7doe** [comment]
fixed by https://github.com/Microsoft/AppCenter-Test-Appium-Java-Extensions/pull/5 and released as [1.5](https://github.com/Microsoft/AppCenter-Test-Appium-Java-Extensions/releases/tag/appium-test-extension-1.5)
